
# A string used to distinguish different Supabase projects on the same host. Defaults to the working
# directory name when running `supabase init`.
project_id = "shiftflex"

[api]
enabled = true
# Port to use for the API URL.
port = 54321
# Schemas to expose in your API. Tables, views and stored procedures in this schema will get API
# endpoints. public and storage are always included.
schemas = ["public", "storage", "graphql_public"]
# Extra schemas to add to the search_path of every request. public is always included.
extra_search_path = ["public", "extensions"]
# Maximum rows to return from a view, table, or stored procedure. Limits payload size for accidental
# or malicious requests.
max_rows = 1000

[db]
# Port to use for the local database URL.
port = 54322
# Port used by db diff command to initialize the shadow database.
shadow_port = 54320
# The database major version to use. This has to be the same as your remote database's. Run `SHOW
# server_version;` on the remote database to check.
major_version = 15

[db.pooler]
enabled = false
# Port to use for the local connection pooler.
port = 54329
# Maximum number of connections to the database.
pool_size = 20
# Maximum connection lifetime.
pool_timeout = 1800
# Maximum time to wait when all connections are busy.
max_client_conn = 100

[studio]
enabled = true
# Port to use for Supabase Studio.
port = 54323
# External URL of the API server that frontend connects to.
api_url = "http://localhost"

# Email testing server. Emails sent with the local dev setup are not actually sent - the emails are
# monitored and accessible from the dashboard.
[inbucket]
enabled = true
# Port to use for the email testing server web interface.
port = 54324
# Uncomment to expose additional ports for testing user applications that send emails.
# smtp_port = 54325
# pop3_port = 54326

[storage]
enabled = true
# The maximum file size allowed (e.g. "5MB", "500KB").
file_size_limit = "50MIB"

[auth]
enabled = true
# The base URL of your website. Used as an allow-list for redirects and for constructing URLs used in
# emails.
site_url = "http://localhost:3000"
# A list of *exact* URLs that auth providers are permitted to redirect to post authentication.
additional_redirect_urls = ["https://localhost:3000"]
# How long tokens are valid for, in seconds. Defaults to 3600 (1 hour), maximum 604,800 (1 week).
jwt_expiry = 3600
# If disabled, the refresh token will never expire.
enable_refresh_token_rotation = true
# Allows refresh tokens to be reused after expiry, up to the specified interval in seconds.
# Requires enable_refresh_token_rotation = true.
refresh_token_reuse_interval = 10
# Allow/disallow new user signups to your project.
enable_signup = true

[auth.email]
# Allow/disallow new user signups via email to your project.
enable_signup = true
# If enabled, a user will be required to confirm any email change on both the old, and new email
# addresses. If disabled, only the new email is required to confirm.
double_confirm_changes = true
# If enabled, users need to confirm their email address before signing in.
enable_confirmations = false

[auth.sms]
# Allow/disallow new user signups via SMS to your project.
enable_signup = true
# If enabled, users need to confirm their phone number before signing in.
enable_confirmations = false

[auth.email_templates.invite]
subject = "You have been invited"
content_path = "./supabase/templates/invite.html"

[auth.email_templates.confirmation]
subject = "Confirm Your Signup"
content_path = "./supabase/templates/confirmation.html"

[auth.email_templates.recovery]
subject = "Reset Your Password"
content_path = "./supabase/templates/recovery.html"

[auth.email_templates.magic_link]
subject = "Your Magic Link"
content_path = "./supabase/templates/magic_link.html"

[auth.email_templates.email_change]
subject = "Confirm Email Change"
content_path = "./supabase/templates/email_change.html"

[auth.email_templates.change_email]
subject = "Email Change"
content_path = "./supabase/templates/change_email.html"

[analytics]
enabled = false
port = 54327
vector_port = 54328
# Configure one of these backends
backend = "postgres"

# Configure these Segment config options
segment_key = ""
segment_writekey = ""

# Comment the functions section to disable the hourly notification
# [functions]
# [functions.hourly_match_notification]
# verify_jwt = true
# schedule = "*/5 * * * *"

[experimental]
# Configure Experimental features
enable_testing_tools = true
