
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ponhfgbpxehsdlxjpszg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBvbmhmZ2JweGVoc2RseGpwc3pnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU5ODM0NDcsImV4cCI6MjA2MTU1OTQ0N30.-n7sUFjxDJUCpMMA0AGnXlQCkaVt31dER91ZQLO3jDs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL, 
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      persistSession: true,
      autoRefreshToken: true,
      storage: typeof window !== 'undefined' ? localStorage : undefined
    }
  }
);

// Add connectivity check function
export const checkSupabaseConnection = async () => {
  try {
    console.log('Testing Supabase connection...');
    const { data, error } = await supabase
      .from('profiles')
      .select('count(*)', { count: 'exact', head: true })
      .limit(1);
      
    if (error) {
      console.error('Supabase connection test failed:', error);
      return { connected: false, error: error.message };
    }
    
    console.log('Supabase connection successful:', data);
    return { connected: true, data };
  } catch (err: any) {
    console.error('Supabase connection error:', err);
    return { connected: false, error: err.message || 'Unknown connection error' };
  }
};

// Initialize connection check on load
if (typeof window !== 'undefined') {
  checkSupabaseConnection().then(result => {
    console.log(`Initial connection check: ${result.connected ? 'SUCCESS' : 'FAILED'}`);
  });
}
